# Testing Saved Model

### 1. Installation

In [1]:
!py -V

Python 3.10.11

In [3]:
!pip install torch==2.9.0

Collecting torch==2.9.0
  Using cached torch-2.9.0-cp312-cp312-win_amd64.whl.metadata (30 kB)
Requirement already satisfied: filelock in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from torch==2.9.0) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from torch==2.9.0) (4.15.0)
Collecting sympy>=1.13.3 (from torch==2.9.0)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: networkx>=2.5.1 in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from torch==2.9.0) (3.5)
Requirement already satisfied: jinja2 in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from torch==2.9.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from torch==2.9.0) (2025.3.0)
Requirement already satisfied: setuptools in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from torch==2.9.0) (80.9.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from sympy>=1.13.3->torch==2.9.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from jinja2->torch==2.9.0) (3.0.3)
Using cached torch-2.9.0-cp312-cp312-win_amd64.whl (109.3 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Installing collected packages: sympy, torch

  Attempting uninstall: sympy

    Found existing installation: sympy 1.13.1

   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
    Uninstalling sympy-1.13.1:
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
      Successfully uninstalled sympy-1.13.1
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
   ---------------------------------------- 0/2 [sympy]
  Attempting uninstall: torch
   ---------------------------------------- 0/2 [sympy]
    Found existing installation: torch 2.4.0+cu121
   ---------------------------------------- 0/2 [sympy]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
    Uninstalling torch-2.4.0+cu121:
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
      Successfully uninstalled torch-2.4.0+cu121
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]
   -------------------- ------------------- 1/2 [torch]

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\USER\Documents\Jawiverse\jawiverse_env\Lib\site-packages\~-rch'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
unsloth 2025.10.11 requires triton-windows; sys_platform == "win32" and (platform_machine == "AMD64" or platform_machine == "x86_64"), which is not installed.
unsloth-zoo 2025.10.12 requires triton-windows; sys_platform == "win32" and (platform_machine == "AMD64" or platform_machine == "x86_64"), which is not installed.
torchaudio 2.5.1+cu121 requires torch==2.5.1+cu121, but you have torch 2.9.0 which is incompatible.
torchvision 0.20.1+cu121 requires torch==2.5.1+cu121, but you have torch 2.9.0 which is incompatible.
xformers 0.0.27.post2 requires torch==2.4.0, but you have torch 2.9.0 which is incompatible.

In [7]:
!pip list

Package           Version
----------------- ------------
asttokens         3.0.0
colorama          0.4.6
comm              0.2.3
debugpy           1.8.17
decorator         5.2.1
exceptiongroup    1.3.0
executing         2.2.1
filelock          3.19.1
fsspec            2025.9.0
ipykernel         7.1.0
ipython           8.37.0
jedi              0.19.2
Jinja2            3.1.3
jupyter_client    8.6.3
jupyter_core      5.9.1
MarkupSafe        2.1.5
matplotlib-inline 0.2.1
mpmath            1.3.0
nest-asyncio      1.6.0
networkx          3.3
numpy             2.1.2
packaging         25.0
parso             0.8.5
pillow            11.3.0
pip               23.0.1
platformdirs      4.5.0
prompt_toolkit    3.0.52
psutil            7.1.3
pure_eval         0.2.3
Pygments          2.19.2
python-dateutil   2.9.0.post0
pyzmq             27.1.0
setuptools        65.5.0
six               1.17.0
stack-data        0.6.3
sympy             1.13.1
torch             2.5.1+cu121
torchaudio        2.5.1+cu121
torchvision       0.20.1+cu121
tornado           6.5.2
traitlets         5.14.3
typing_extensions 4.9.0
wcwidth           0.2.14

[notice] A new release of pip is available: 23.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import torch

print(f"CUDA available: {torch.cuda.is_available()}")
print(f"CUDA version: {torch.version.cuda}")
print(f"Device count: {torch.cuda.device_count()}")
if torch.cuda.is_available():
    print(f"Device name: {torch.cuda.get_device_name(0)}")

CUDA available: True
CUDA version: 12.1
Device count: 1
Device name: NVIDIA GeForce GTX 1650

In [4]:
import torch
print(torch.__version__)
print(torch.version.cuda)

2.6.0+cpu
None

In [8]:
# --- Install requirements if not yet done ---
!pip install -r jawirumi_v1_model\requirements.txt

Collecting accelerate==1.11.0
  Using cached accelerate-1.11.0-py3-none-any.whl (375 kB)
Collecting bitsandbytes==0.48.1
  Using cached bitsandbytes-0.48.1-py3-none-win_amd64.whl (59.5 MB)
Collecting datasets==3.6.0
  Using cached datasets-3.6.0-py3-none-any.whl (491 kB)
Collecting fastrlock==0.8.3
  Using cached fastrlock-0.8.3-cp310-cp310-win_amd64.whl (30 kB)
Collecting hf_transfer==0.1.9
  Using cached hf_transfer-0.1.9-cp38-abi3-win_amd64.whl (1.2 MB)
Collecting peft==0.17.1
  Using cached peft-0.17.1-py3-none-any.whl (504 kB)
Collecting protobuf==5.29.5
  Using cached protobuf-5.29.5-cp310-abi3-win_amd64.whl (434 kB)
Collecting sentence-transformers==5.1.2
  Using cached sentence_transformers-5.1.2-py3-none-any.whl (488 kB)
Collecting sentencepiece==0.2.1
  Using cached sentencepiece-0.2.1-cp310-cp310-win_amd64.whl (1.1 MB)
Collecting transformers==4.55.4
  Using cached transformers-4.55.4-py3-none-any.whl (11.3 MB)
Collecting trl==0.22.2
  Using cached trl-0.22.2-py3-none-any.whl (544 kB)
Collecting unsloth==2025.10.11
  Using cached unsloth-2025.10.11-py3-none-any.whl (347 kB)
Collecting unsloth_zoo==2025.10.12
  Using cached unsloth_zoo-2025.10.12-py3-none-any.whl (272 kB)
Collecting vega-datasets==0.9.0
  Using cached vega_datasets-0.9.0-py3-none-any.whl (210 kB)
Collecting evaluate==0.4.6
  Using cached evaluate-0.4.6-py3-none-any.whl (84 kB)
Collecting sacrebleu==2.5.1
  Using cached sacrebleu-2.5.1-py3-none-any.whl (104 kB)
Collecting jiwer==4.0.0
  Using cached jiwer-4.0.0-py3-none-any.whl (23 kB)
Requirement already satisfied: numpy>=1.17 in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from accelerate==1.11.0->-r jawirumi_v1_model\requirements.txt (line 1)) (2.1.2)
Collecting safetensors>=0.4.3
  Using cached safetensors-0.6.2-cp38-abi3-win_amd64.whl (320 kB)
Requirement already satisfied: torch>=2.0.0 in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from accelerate==1.11.0->-r jawirumi_v1_model\requirements.txt (line 1)) (2.5.1+cu121)
Requirement already satisfied: packaging>=20.0 in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from accelerate==1.11.0->-r jawirumi_v1_model\requirements.txt (line 1)) (25.0)
Requirement already satisfied: psutil in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from accelerate==1.11.0->-r jawirumi_v1_model\requirements.txt (line 1)) (7.1.3)
Collecting pyyaml
  Using cached pyyaml-6.0.3-cp310-cp310-win_amd64.whl (158 kB)
Collecting huggingface_hub>=0.21.0
  Using cached huggingface_hub-1.1.4-py3-none-any.whl (515 kB)
Collecting multiprocess<0.70.17
  Using cached multiprocess-0.70.16-py310-none-any.whl (134 kB)
Collecting xxhash
  Using cached xxhash-3.6.0-cp310-cp310-win_amd64.whl (31 kB)
Collecting fsspec[http]<=2025.3.0,>=2023.1.0
  Using cached fsspec-2025.3.0-py3-none-any.whl (193 kB)
Collecting tqdm>=4.66.3
  Using cached tqdm-4.67.1-py3-none-any.whl (78 kB)
Collecting dill<0.3.9,>=0.3.0
  Using cached dill-0.3.8-py3-none-any.whl (116 kB)
Collecting pandas
  Using cached pandas-2.3.3-cp310-cp310-win_amd64.whl (11.3 MB)
Requirement already satisfied: filelock in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from datasets==3.6.0->-r jawirumi_v1_model\requirements.txt (line 3)) (3.19.1)
Collecting requests>=2.32.2
  Using cached requests-2.32.5-py3-none-any.whl (64 kB)
Collecting pyarrow>=15.0.0
  Using cached pyarrow-22.0.0-cp310-cp310-win_amd64.whl (28.1 MB)
Requirement already satisfied: typing_extensions>=4.5.0 in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from sentence-transformers==5.1.2->-r jawirumi_v1_model\requirements.txt (line 8)) (4.9.0)
Collecting scipy
  Using cached scipy-1.15.3-cp310-cp310-win_amd64.whl (41.3 MB)
Requirement already satisfied: Pillow in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from sentence-transformers==5.1.2->-r jawirumi_v1_model\requirements.txt (line 8)) (11.3.0)
Collecting scikit-learn
  Using cached scikit_learn-1.7.2-cp310-cp310-win_amd64.whl (8.9 MB)
Collecting regex!=2019.12.17
  Using cached regex-2025.11.3-cp310-cp310-win_amd64.whl (277 kB)
Collecting tokenizers<0.22,>=0.21
  Using cached tokenizers-0.21.4-cp39-abi3-win_amd64.whl (2.5 MB)
Collecting huggingface_hub>=0.21.0
  Using cached huggingface_hub-0.36.0-py3-none-any.whl (566 kB)
Collecting wheel>=0.42.0
  Using cached wheel-0.45.1-py3-none-any.whl (72 kB)
Collecting triton-windows
  Using cached triton_windows-3.5.1.post21-cp310-cp310-win_amd64.whl (46.5 MB)
Collecting xformers>=0.0.27.post2
  Using cached xformers-0.0.33.post1-cp39-abi3-win_amd64.whl (105.1 MB)
Collecting tyro
  Using cached tyro-0.9.35-py3-none-any.whl (132 kB)
Requirement already satisfied: torchvision in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from unsloth==2025.10.11->-r jawirumi_v1_model\requirements.txt (line 12)) (0.20.1+cu121)
Collecting diffusers
  Using cached diffusers-0.35.2-py3-none-any.whl (4.1 MB)
Collecting msgspec
  Using cached msgspec-0.19.0-cp310-cp310-win_amd64.whl (186 kB)
Collecting torchao>=0.13.0
  Using cached torchao-0.14.1-py3-none-any.whl (1.1 MB)
Collecting cut_cross_entropy
  Using cached cut_cross_entropy-25.1.1-py3-none-any.whl (22 kB)
Collecting lxml
  Using cached lxml-6.0.2-cp310-cp310-win_amd64.whl (4.0 MB)
Collecting tabulate>=0.8.9
  Using cached tabulate-0.9.0-py3-none-any.whl (35 kB)
Requirement already satisfied: colorama in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from sacrebleu==2.5.1->-r jawirumi_v1_model\requirements.txt (line 16)) (0.4.6)
Collecting portalocker
  Using cached portalocker-3.2.0-py3-none-any.whl (22 kB)
Collecting click>=8.1.8
  Using cached click-8.3.0-py3-none-any.whl (107 kB)
Collecting rapidfuzz>=3.9.7
  Using cached rapidfuzz-3.14.3-cp310-cp310-win_amd64.whl (1.5 MB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1
  Using cached aiohttp-3.13.2-cp310-cp310-win_amd64.whl (455 kB)
Collecting charset_normalizer<4,>=2
  Using cached charset_normalizer-3.4.4-cp310-cp310-win_amd64.whl (107 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.5.0-py3-none-any.whl (129 kB)
Collecting idna<4,>=2.5
  Using cached idna-3.11-py3-none-any.whl (71 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2025.11.12-py3-none-any.whl (159 kB)
Requirement already satisfied: jinja2 in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from torch>=2.0.0->accelerate==1.11.0->-r jawirumi_v1_model\requirements.txt (line 1)) (3.1.3)
Requirement already satisfied: networkx in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from torch>=2.0.0->accelerate==1.11.0->-r jawirumi_v1_model\requirements.txt (line 1)) (3.3)
Requirement already satisfied: sympy==1.13.1 in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from torch>=2.0.0->accelerate==1.11.0->-r jawirumi_v1_model\requirements.txt (line 1)) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from sympy==1.13.1->torch>=2.0.0->accelerate==1.11.0->-r jawirumi_v1_model\requirements.txt (line 1)) (1.3.0)
Collecting torch>=2.0.0
  Using cached torch-2.9.0-cp310-cp310-win_amd64.whl (109.3 MB)
Collecting typing_extensions>=4.5.0
  Using cached typing_extensions-4.15.0-py3-none-any.whl (44 kB)
INFO: pip is looking at multiple versions of xformers to determine which version is compatible with other requirements. This could take a while.
Collecting xformers>=0.0.27.post2
  Using cached xformers-0.0.33-cp39-abi3-win_amd64.whl (8.3 MB)
  Using cached xformers-0.0.32.post2-cp39-abi3-win_amd64.whl (100.2 MB)
Collecting torch>=2.0.0
  Using cached torch-2.8.0-cp310-cp310-win_amd64.whl (241.4 MB)
Collecting xformers>=0.0.27.post2
  Using cached xformers-0.0.32.post1-cp39-abi3-win_amd64.whl (100.2 MB)
  Using cached xformers-0.0.31.post1-cp39-abi3-win_amd64.whl (100.2 MB)
Collecting torch>=2.0.0
  Using cached torch-2.7.1-cp310-cp310-win_amd64.whl (216.1 MB)
Collecting xformers>=0.0.27.post2
  Using cached xformers-0.0.31-cp39-abi3-win_amd64.whl (100.2 MB)
  Using cached xformers-0.0.30-cp310-cp310-win_amd64.whl (108.0 MB)
Collecting torch>=2.0.0
  Using cached torch-2.7.0-cp310-cp310-win_amd64.whl (212.5 MB)
Collecting xformers>=0.0.27.post2
  Using cached xformers-0.0.29.post3-cp310-cp310-win_amd64.whl (167.7 MB)
Collecting torch>=2.0.0
  Using cached torch-2.6.0-cp310-cp310-win_amd64.whl (204.2 MB)
Collecting importlib_metadata
  Using cached importlib_metadata-8.7.0-py3-none-any.whl (27 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from pandas->datasets==3.6.0->-r jawirumi_v1_model\requirements.txt (line 3)) (2.9.0.post0)
Collecting tzdata>=2022.7
  Using cached tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Collecting pytz>=2020.1
  Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Collecting pywin32>=226
  Using cached pywin32-311-cp310-cp310-win_amd64.whl (9.6 MB)
Collecting threadpoolctl>=3.1.0
  Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Collecting joblib>=1.2.0
  Using cached joblib-1.5.2-py3-none-any.whl (308 kB)
Collecting torchvision
  Using cached torchvision-0.24.1-cp310-cp310-win_amd64.whl (3.7 MB)
  Downloading torchvision-0.24.0-cp310-cp310-win_amd64.whl (3.7 MB)
     ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
     ------ --------------------------------- 0.6/3.7 MB 13.6 MB/s eta 0:00:01
     --------------------- ------------------ 1.9/3.7 MB 24.8 MB/s eta 0:00:01
     ---------------------------------------  3.7/3.7 MB 29.4 MB/s eta 0:00:01
     ---------------------------------------- 3.7/3.7 MB 26.3 MB/s eta 0:00:00
  Using cached torchvision-0.23.0-cp310-cp310-win_amd64.whl (1.6 MB)
  Downloading torchvision-0.22.1-cp310-cp310-win_amd64.whl (1.7 MB)
     ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ------------------------ --------------- 1.0/1.7 MB 64.6 MB/s eta 0:00:01
     ---------------------------------------- 1.7/1.7 MB 1.9 MB/s eta 0:00:00
  Downloading torchvision-0.22.0-cp310-cp310-win_amd64.whl (1.7 MB)
     ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
     ---------------------------------------- 1.7/1.7 MB 36.3 MB/s eta 0:00:00
  Downloading torchvision-0.21.0-cp310-cp310-win_amd64.whl (1.6 MB)
     ---------------------------------------- 0.0/1.6 MB ? eta -:--:--
     ---------------------------------------- 1.6/1.6 MB 33.0 MB/s eta 0:00:00
Collecting docstring-parser>=0.15
  Using cached docstring_parser-0.17.0-py3-none-any.whl (36 kB)
Collecting typeguard>=4.0.0
  Using cached typeguard-4.4.4-py3-none-any.whl (34 kB)
Collecting rich>=11.1.0
  Downloading rich-14.2.0-py3-none-any.whl (243 kB)
     ---------------------------------------- 0.0/243.4 kB ? eta -:--:--
     ------------------------------------- 243.4/243.4 kB 14.6 MB/s eta 0:00:00
Collecting shtab>=1.5.6
  Using cached shtab-1.7.2-py3-none-any.whl (14 kB)
Collecting yarl<2.0,>=1.17.0
  Downloading yarl-1.22.0-cp310-cp310-win_amd64.whl (86 kB)
     ---------------------------------------- 0.0/86.9 kB ? eta -:--:--
     ---------------------------------------- 86.9/86.9 kB ? eta 0:00:00
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.8.0-cp310-cp310-win_amd64.whl (43 kB)
     ---------------------------------------- 0.0/43.8 kB ? eta -:--:--
     ---------------------------------------- 43.8/43.8 kB 2.2 MB/s eta 0:00:00
Collecting multidict<7.0,>=4.5
  Downloading multidict-6.7.0-cp310-cp310-win_amd64.whl (46 kB)
     ---------------------------------------- 0.0/46.0 kB ? eta -:--:--
     ---------------------------------------- 46.0/46.0 kB 2.2 MB/s eta 0:00:00
Collecting attrs>=17.3.0
  Using cached attrs-25.4.0-py3-none-any.whl (67 kB)
Collecting async-timeout<6.0,>=4.0
  Using cached async_timeout-5.0.1-py3-none-any.whl (6.2 kB)
Collecting propcache>=0.2.0
  Downloading propcache-0.4.1-cp310-cp310-win_amd64.whl (41 kB)
     ---------------------------------------- 0.0/41.6 kB ? eta -:--:--
     ---------------------------------------- 41.6/41.6 kB ? eta 0:00:00
Collecting aiosignal>=1.4.0
  Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Collecting aiohappyeyeballs>=2.5.0
  Using cached aiohappyeyeballs-2.6.1-py3-none-any.whl (15 kB)
Requirement already satisfied: six>=1.5 in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets==3.6.0->-r jawirumi_v1_model\requirements.txt (line 3)) (1.17.0)
Collecting markdown-it-py>=2.2.0
  Using cached markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from rich>=11.1.0->tyro->unsloth==2025.10.11->-r jawirumi_v1_model\requirements.txt (line 12)) (2.19.2)
Collecting zipp>=3.20
  Using cached zipp-3.23.0-py3-none-any.whl (10 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\documents\jawiverse\jawiverse_env_310\lib\site-packages (from jinja2->torch>=2.0.0->accelerate==1.11.0->-r jawirumi_v1_model\requirements.txt (line 1)) (2.1.5)
Collecting mdurl~=0.1
  Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Installing collected packages: torchao, pywin32, pytz, fastrlock, zipp, xxhash, wheel, urllib3, tzdata, typing_extensions, triton-windows, tqdm, threadpoolctl, tabulate, shtab, sentencepiece, scipy, safetensors, regex, rapidfuzz, pyyaml, pyarrow, protobuf, propcache, portalocker, msgspec, mdurl, lxml, joblib, idna, hf_transfer, fsspec, frozenlist, docstring-parser, dill, click, charset_normalizer, certifi, attrs, async-timeout, aiohappyeyeballs, typeguard, torch, scikit-learn, sacrebleu, requests, pandas, multiprocess, multidict, markdown-it-py, jiwer, importlib_metadata, aiosignal, yarl, xformers, vega-datasets, torchvision, rich, huggingface_hub, cut_cross_entropy, bitsandbytes, tyro, tokenizers, diffusers, aiohttp, accelerate, transformers, sentence-transformers, peft, datasets, trl, evaluate, unsloth_zoo, unsloth
  Attempting uninstall: typing_extensions
    Found existing installation: typing_extensions 4.9.0
    Uninstalling typing_extensions-4.9.0:
      Successfully uninstalled typing_extensions-4.9.0
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.9.0
    Uninstalling fsspec-2025.9.0:
      Successfully uninstalled fsspec-2025.9.0
  Attempting uninstall: torch
    Found existing installation: torch 2.5.1+cu121
    Uninstalling torch-2.5.1+cu121:
      Successfully uninstalled torch-2.5.1+cu121

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\USER\\Documents\\Jawiverse\\jawiverse_env_310\\Lib\\site-packages\\~orch\\lib\\asmjit.dll'
Check the permissions.


[notice] A new release of pip is available: 23.0.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
# --- Import after installation ---
from unsloth import FastLanguageModel

# --- Load once (already trained + saved) ---
def load_model(model_path="lora_model", max_seq_length=2048, dtype=None, load_in_4bit=True):
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=model_path,
        max_seq_length=max_seq_length,
        dtype=dtype,
        load_in_4bit=load_in_4bit,
    )
    FastLanguageModel.for_inference(model)
    return model, tokenizer

ImportError: Unsloth: Please install unsloth_zoo via `pip install unsloth_zoo` then retry!

:

In [11]:
!python -m xformers.info

WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.9.0+cu128 with CUDA 1208 (you have 2.9.0+cpu)
    Python  3.10.11 (you have 3.12.8)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
c:\Users\USER\Documents\Jawiverse\jawiverse_env\Lib\site-packages\triton\knobs.py:212: UserWarning: Failed to find cuobjdump.exe
  warnings.warn(f"Failed to find {binary}")
c:\Users\USER\Documents\Jawiverse\jawiverse_env\Lib\site-packages\triton\knobs.py:212: UserWarning: Failed to find nvdisasm.exe
  warnings.warn(f"Failed to find {binary}")
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\USER\Documents\Jawiverse\jawiverse_env\Lib\site-packages\xformers\info.py", line 11, in <module>
    from . import __version__, _cpp_lib, _is_opensource, _is_triton_available, ops
  File "c:\Users\USER\Documents\Jawiverse\jawiverse_env\Lib\site-packages\xformers\ops\__init__.py", line 9, in <module>
    from .fmha import (
  File "c:\Users\USER\Documents\Jawiverse\jawiverse_env\Lib\site-packages\xformers\ops\fmha\__init__.py", line 10, in <module>
    from . import (
  File "c:\Users\USER\Documents\Jawiverse\jawiverse_env\Lib\site-packages\xformers\ops\fmha\flash3.py", line 110, in <module>
    from ...flash_attn_3 import _C  # type: ignore[attr-defined]  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _C: The specified module could not be found.

In [10]:
!pip install --pre -U xformers

Requirement already satisfied: xformers in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (0.0.33.post1)
Collecting xformers
  Downloading xformers-0.0.34.dev1096-cp39-abi3-win_amd64.whl.metadata (1.0 kB)
Requirement already satisfied: numpy in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from xformers) (2.3.3)
Requirement already satisfied: torch==2.9.0 in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from xformers) (2.9.0)
Requirement already satisfied: filelock in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from torch==2.9.0->xformers) (3.19.1)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from torch==2.9.0->xformers) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from torch==2.9.0->xformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from torch==2.9.0->xformers) (3.5)
Requirement already satisfied: jinja2 in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from torch==2.9.0->xformers) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from torch==2.9.0->xformers) (2025.3.0)
Requirement already satisfied: setuptools in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from torch==2.9.0->xformers) (70.2.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from sympy>=1.13.3->torch==2.9.0->xformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\user\documents\jawiverse\jawiverse_env\lib\site-packages (from jinja2->torch==2.9.0->xformers) (2.1.5)
Downloading xformers-0.0.34.dev1096-cp39-abi3-win_amd64.whl (105.1 MB)
   ---------------------------------------- 0.0/105.1 MB ? eta -:--:--
   ---------------------------------------- 1.0/105.1 MB 49.2 MB/s eta 0:00:03
    --------------------------------------- 2.1/105.1 MB 6.9 MB/s eta 0:00:15
    --------------------------------------- 2.1/105.1 MB 6.9 MB/s eta 0:00:15
   - -------------------------------------- 3.1/105.1 MB 4.5 MB/s eta 0:00:23
   - -------------------------------------- 3.1/105.1 MB 4.5 MB/s eta 0:00:23
   - -------------------------------------- 3.7/105.1 MB 2.8 MB/s eta 0:00:37
   - -------------------------------------- 4.2/105.1 MB 3.2 MB/s eta 0:00:32
   - -------------------------------------- 5.2/105.1 MB 3.2 MB/s eta 0:00:32
   - -------------------------------------- 5.2/105.1 MB 3.2 MB/s eta 0:00:32
   -- ------------------------------------- 6.3/105.1 MB 3.2 MB/s eta 0:00:31
   -- ------------------------------------- 7.3/105.1 MB 3.2 MB/s eta 0:00:31
   -- ------------------------------------- 7.3/105.1 MB 3.2 MB/s eta 0:00:31
   --- ------------------------------------ 8.4/105.1 MB 3.3 MB/s eta 0:00:30
   --- ------------------------------------ 9.4/105.1 MB 3.4 MB/s eta 0:00:29
   --- ------------------------------------ 10.5/105.1 MB 3.4 MB/s eta 0:00:29
   --- ------------------------------------ 10.5/105.1 MB 3.4 MB/s eta 0:00:29
   ---- ----------------------------------- 11.5/105.1 MB 3.4 MB/s eta 0:00:28
   ---- ----------------------------------- 11.8/105.1 MB 3.1 MB/s eta 0:00:30
   ---- ----------------------------------- 12.6/105.1 MB 3.3 MB/s eta 0:00:28
   ----- ---------------------------------- 13.6/105.1 MB 3.3 MB/s eta 0:00:28
   ----- ---------------------------------- 13.6/105.1 MB 3.3 MB/s eta 0:00:28
   ----- ---------------------------------- 14.7/105.1 MB 3.3 MB/s eta 0:00:28
   ----- ---------------------------------- 14.7/105.1 MB 3.3 MB/s eta 0:00:28
   ----- ---------------------------------- 15.7/105.1 MB 3.3 MB/s eta 0:00:28
   ----- ---------------------------------- 15.7/105.1 MB 3.3 MB/s eta 0:00:28
   ------ --------------------------------- 16.8/105.1 MB 3.2 MB/s eta 0:00:28
   ------ --------------------------------- 17.8/105.1 MB 3.3 MB/s eta 0:00:27
   ------ --------------------------------- 17.8/105.1 MB 3.3 MB/s eta 0:00:27
   ------ --------------------------------- 17.8/105.1 MB 3.3 MB/s eta 0:00:27
   ------- -------------------------------- 18.9/105.1 MB 3.1 MB/s eta 0:00:28
   ------- -------------------------------- 19.9/105.1 MB 3.1 MB/s eta 0:00:28
   ------- -------------------------------- 19.9/105.1 MB 3.1 MB/s eta 0:00:28
   ------- -------------------------------- 19.9/105.1 MB 3.1 MB/s eta 0:00:28
   ------- -------------------------------- 21.0/105.1 MB 3.0 MB/s eta 0:00:28
   -------- ------------------------------- 22.0/105.1 MB 3.1 MB/s eta 0:00:27
   -------- ------------------------------- 22.0/105.1 MB 3.1 MB/s eta 0:00:27
   -------- ------------------------------- 23.1/105.1 MB 3.1 MB/s eta 0:00:27
   -------- ------------------------------- 23.1/105.1 MB 3.1 MB/s eta 0:00:27
   -------- ------------------------------- 23.1/105.1 MB 3.1 MB/s eta 0:00:27
   -------- ------------------------------- 23.1/105.1 MB 3.1 MB/s eta 0:00:27
   -------- ------------------------------- 23.1/105.1 MB 3.1 MB/s eta 0:00:27
   -------- ------------------------------- 23.1/105.1 MB 3.1 MB/s eta 0:00:27
   -------- ------------------------------- 23.1/105.1 MB 3.1 MB/s eta 0:00:27
   --------- ------------------------------ 24.1/105.1 MB 2.7 MB/s eta 0:00:31
   --------- ------------------------------ 24.1/105.1 MB 2.7 MB/s eta 0:00:31
   --------- ------------------------------ 25.2/105.1 MB 2.7 MB/s eta 0:00:30
   --------- ------------------------------ 26.2/105.1 MB 2.7 MB/s eta 0:00:29
   ---------- ----------------------------- 27.3/105.1 MB 2.8 MB/s eta 0:00:29
   ---------- ----------------------------- 27.3/105.1 MB 2.8 MB/s eta 0:00:29
   ---------- ----------------------------- 27.5/105.1 MB 2.7 MB/s eta 0:00:29
   ---------- ----------------------------- 28.3/105.1 MB 2.7 MB/s eta 0:00:29
   ----------- ---------------------------- 29.4/105.1 MB 2.8 MB/s eta 0:00:28
   ----------- ---------------------------- 29.4/105.1 MB 2.8 MB/s eta 0:00:28
   ----------- ---------------------------- 30.4/105.1 MB 2.8 MB/s eta 0:00:27
   ----------- ---------------------------- 30.4/105.1 MB 2.8 MB/s eta 0:00:27
   ----------- ---------------------------- 31.5/105.1 MB 2.8 MB/s eta 0:00:27
   ------------ --------------------------- 32.5/105.1 MB 2.8 MB/s eta 0:00:26
   ------------ --------------------------- 32.5/105.1 MB 2.8 MB/s eta 0:00:26
   ------------ --------------------------- 33.6/105.1 MB 2.8 MB/s eta 0:00:26
   ------------ --------------------------- 33.6/105.1 MB 2.8 MB/s eta 0:00:26
   ------------ --------------------------- 33.6/105.1 MB 2.8 MB/s eta 0:00:26
   ------------ --------------------------- 33.6/105.1 MB 2.8 MB/s eta 0:00:26
   ------------- -------------------------- 34.6/105.1 MB 2.7 MB/s eta 0:00:27
   ------------- -------------------------- 34.6/105.1 MB 2.7 MB/s eta 0:00:27
   ------------- -------------------------- 35.7/105.1 MB 2.7 MB/s eta 0:00:26
   ------------- -------------------------- 35.7/105.1 MB 2.7 MB/s eta 0:00:26
   ------------- -------------------------- 36.7/105.1 MB 2.7 MB/s eta 0:00:26
   -------------- ------------------------- 37.7/105.1 MB 2.7 MB/s eta 0:00:25
   -------------- ------------------------- 37.7/105.1 MB 2.7 MB/s eta 0:00:25
   -------------- ------------------------- 38.8/105.1 MB 2.7 MB/s eta 0:00:25
   -------------- ------------------------- 38.8/105.1 MB 2.7 MB/s eta 0:00:25
   -------------- ------------------------- 38.8/105.1 MB 2.7 MB/s eta 0:00:25
   -------------- ------------------------- 38.8/105.1 MB 2.7 MB/s eta 0:00:25
   -------------- ------------------------- 38.8/105.1 MB 2.7 MB/s eta 0:00:25
   -------------- ------------------------- 39.1/105.1 MB 2.5 MB/s eta 0:00:27
   --------------- ------------------------ 39.8/105.1 MB 2.6 MB/s eta 0:00:26
   --------------- ------------------------ 40.9/105.1 MB 2.6 MB/s eta 0:00:25
   --------------- ------------------------ 40.9/105.1 MB 2.6 MB/s eta 0:00:25
   --------------- ------------------------ 41.9/105.1 MB 2.6 MB/s eta 0:00:25
   ---------------- ----------------------- 43.0/105.1 MB 2.6 MB/s eta 0:00:24
   ---------------- ----------------------- 43.0/105.1 MB 2.6 MB/s eta 0:00:24
   ---------------- ----------------------- 44.0/105.1 MB 2.6 MB/s eta 0:00:24
   ----------------- ---------------------- 45.1/105.1 MB 2.7 MB/s eta 0:00:23
   ----------------- ---------------------- 45.1/105.1 MB 2.7 MB/s eta 0:00:23
   ----------------- ---------------------- 46.1/105.1 MB 2.7 MB/s eta 0:00:23
   ----------------- ---------------------- 47.2/105.1 MB 2.7 MB/s eta 0:00:22
   ----------------- ---------------------- 47.2/105.1 MB 2.7 MB/s eta 0:00:22
   ----------------- ---------------------- 47.2/105.1 MB 2.7 MB/s eta 0:00:22
   ------------------ --------------------- 48.2/105.1 MB 2.7 MB/s eta 0:00:22
   ------------------ --------------------- 49.3/105.1 MB 2.7 MB/s eta 0:00:21
   ------------------ --------------------- 49.3/105.1 MB 2.7 MB/s eta 0:00:21
   ------------------- -------------------- 50.3/105.1 MB 2.7 MB/s eta 0:00:21
   ------------------- -------------------- 50.6/105.1 MB 2.6 MB/s eta 0:00:21
   ------------------- -------------------- 51.4/105.1 MB 2.7 MB/s eta 0:00:20
   ------------------- -------------------- 52.4/105.1 MB 2.7 MB/s eta 0:00:20
   ------------------- -------------------- 52.4/105.1 MB 2.7 MB/s eta 0:00:20
   -------------------- ------------------- 53.5/105.1 MB 2.7 MB/s eta 0:00:20
   -------------------- ------------------- 53.5/105.1 MB 2.7 MB/s eta 0:00:20
   -------------------- ------------------- 53.5/105.1 MB 2.7 MB/s eta 0:00:20
   -------------------- ------------------- 53.5/105.1 MB 2.7 MB/s eta 0:00:20
   -------------------- ------------------- 53.5/105.1 MB 2.7 MB/s eta 0:00:20
   -------------------- ------------------- 54.5/105.1 MB 2.6 MB/s eta 0:00:20
   --------------------- ------------------ 55.6/105.1 MB 2.6 MB/s eta 0:00:19
   --------------------- ------------------ 55.6/105.1 MB 2.6 MB/s eta 0:00:19
   --------------------- ------------------ 56.6/105.1 MB 2.6 MB/s eta 0:00:19
   --------------------- ------------------ 57.7/105.1 MB 2.7 MB/s eta 0:00:18
   --------------------- ------------------ 57.7/105.1 MB 2.7 MB/s eta 0:00:18
   ---------------------- ----------------- 58.7/105.1 MB 2.7 MB/s eta 0:00:18
   ---------------------- ----------------- 58.7/105.1 MB 2.7 MB/s eta 0:00:18
   ---------------------- ----------------- 59.8/105.1 MB 2.7 MB/s eta 0:00:18
   ----------------------- ---------------- 60.8/105.1 MB 2.7 MB/s eta 0:00:17
   ----------------------- ---------------- 60.8/105.1 MB 2.7 MB/s eta 0:00:17
   ----------------------- ---------------- 61.9/105.1 MB 2.7 MB/s eta 0:00:17
   ----------------------- ---------------- 61.9/105.1 MB 2.7 MB/s eta 0:00:17
   ----------------------- ---------------- 61.9/105.1 MB 2.7 MB/s eta 0:00:17
   ----------------------- ---------------- 61.9/105.1 MB 2.7 MB/s eta 0:00:17
   ----------------------- ---------------- 62.9/105.1 MB 2.6 MB/s eta 0:00:17
   ------------------------ --------------- 64.0/105.1 MB 2.6 MB/s eta 0:00:16
   ------------------------ --------------- 64.0/105.1 MB 2.6 MB/s eta 0:00:16
   ------------------------ --------------- 65.0/105.1 MB 2.6 MB/s eta 0:00:16
   ------------------------ --------------- 65.0/105.1 MB 2.6 MB/s eta 0:00:16
   ------------------------- -------------- 66.1/105.1 MB 2.7 MB/s eta 0:00:15
   ------------------------- -------------- 67.1/105.1 MB 2.7 MB/s eta 0:00:15
   ------------------------- -------------- 67.1/105.1 MB 2.7 MB/s eta 0:00:15
   ------------------------- -------------- 68.2/105.1 MB 2.7 MB/s eta 0:00:14
   ------------------------- -------------- 68.2/105.1 MB 2.7 MB/s eta 0:00:14
   -------------------------- ------------- 69.2/105.1 MB 2.7 MB/s eta 0:00:14
   -------------------------- ------------- 70.3/105.1 MB 2.7 MB/s eta 0:00:13
   --------------------------- ------------ 71.3/105.1 MB 2.7 MB/s eta 0:00:13
   --------------------------- ------------ 71.3/105.1 MB 2.7 MB/s eta 0:00:13
   --------------------------- ------------ 71.3/105.1 MB 2.7 MB/s eta 0:00:13
   --------------------------- ------------ 72.4/105.1 MB 2.7 MB/s eta 0:00:13
   --------------------------- ------------ 73.4/105.1 MB 2.7 MB/s eta 0:00:12
   ---------------------------- ----------- 74.4/105.1 MB 2.7 MB/s eta 0:00:12
   ---------------------------- ----------- 74.4/105.1 MB 2.7 MB/s eta 0:00:12
   ---------------------------- ----------- 75.5/105.1 MB 2.7 MB/s eta 0:00:11
   ----------------------------- ---------- 76.5/105.1 MB 2.7 MB/s eta 0:00:11
   ----------------------------- ---------- 76.5/105.1 MB 2.7 MB/s eta 0:00:11
   ----------------------------- ---------- 77.6/105.1 MB 2.7 MB/s eta 0:00:11
   ----------------------------- ---------- 78.6/105.1 MB 2.7 MB/s eta 0:00:10
   ------------------------------ --------- 79.7/105.1 MB 2.7 MB/s eta 0:00:10
   ------------------------------ --------- 79.7/105.1 MB 2.7 MB/s eta 0:00:10
   ------------------------------ --------- 80.7/105.1 MB 2.8 MB/s eta 0:00:09
   ------------------------------ --------- 81.0/105.1 MB 2.7 MB/s eta 0:00:09
   ------------------------------- -------- 81.8/105.1 MB 2.8 MB/s eta 0:00:09
   ------------------------------- -------- 82.8/105.1 MB 2.8 MB/s eta 0:00:09
   ------------------------------- -------- 83.4/105.1 MB 2.7 MB/s eta 0:00:08
   ------------------------------- -------- 83.9/105.1 MB 2.8 MB/s eta 0:00:08
   -------------------------------- ------- 84.9/105.1 MB 2.8 MB/s eta 0:00:08
   -------------------------------- ------- 84.9/105.1 MB 2.8 MB/s eta 0:00:08
   -------------------------------- ------- 86.0/105.1 MB 2.8 MB/s eta 0:00:07
   --------------------------------- ------ 87.0/105.1 MB 2.8 MB/s eta 0:00:07
   --------------------------------- ------ 88.1/105.1 MB 2.8 MB/s eta 0:00:07
   --------------------------------- ------ 88.1/105.1 MB 2.8 MB/s eta 0:00:07
   --------------------------------- ------ 89.1/105.1 MB 2.8 MB/s eta 0:00:06
   ---------------------------------- ----- 89.9/105.1 MB 2.8 MB/s eta 0:00:06
   ---------------------------------- ----- 90.2/105.1 MB 2.8 MB/s eta 0:00:06
   ---------------------------------- ----- 91.2/105.1 MB 2.8 MB/s eta 0:00:05
   ----------------------------------- ---- 92.3/105.1 MB 2.8 MB/s eta 0:00:05
   ----------------------------------- ---- 92.3/105.1 MB 2.8 MB/s eta 0:00:05
   ----------------------------------- ---- 93.3/105.1 MB 2.8 MB/s eta 0:00:05
   ----------------------------------- ---- 93.3/105.1 MB 2.8 MB/s eta 0:00:05
   ----------------------------------- ---- 94.4/105.1 MB 2.8 MB/s eta 0:00:04
   ----------------------------------- ---- 94.4/105.1 MB 2.8 MB/s eta 0:00:04
   ------------------------------------ --- 95.4/105.1 MB 2.8 MB/s eta 0:00:04
   ------------------------------------ --- 96.5/105.1 MB 2.8 MB/s eta 0:00:04
   ------------------------------------- -- 97.5/105.1 MB 2.8 MB/s eta 0:00:03
   ------------------------------------- -- 97.5/105.1 MB 2.8 MB/s eta 0:00:03
   ------------------------------------- -- 98.6/105.1 MB 2.8 MB/s eta 0:00:03
   ------------------------------------- -- 98.6/105.1 MB 2.8 MB/s eta 0:00:03
   ------------------------------------- -- 98.6/105.1 MB 2.8 MB/s eta 0:00:03
   ------------------------------------- -- 98.6/105.1 MB 2.8 MB/s eta 0:00:03
   ------------------------------------- -- 99.1/105.1 MB 2.7 MB/s eta 0:00:03
   ------------------------------------- -- 99.6/105.1 MB 2.8 MB/s eta 0:00:02
   ------------------------------------- -- 99.6/105.1 MB 2.8 MB/s eta 0:00:02
   -------------------------------------- - 100.7/105.1 MB 2.7 MB/s eta 0:00:02
   -------------------------------------- - 100.7/105.1 MB 2.7 MB/s eta 0:00:02
   -------------------------------------- - 101.7/105.1 MB 2.8 MB/s eta 0:00:02
   ---------------------------------------  102.8/105.1 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  103.8/105.1 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  103.8/105.1 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  104.9/105.1 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------  104.9/105.1 MB 2.8 MB/s eta 0:00:01
   ---------------------------------------- 105.1/105.1 MB 2.9 MB/s eta 0:00:00
Installing collected packages: xformers
  Attempting uninstall: xformers
    Found existing installation: xformers 0.0.33.post1
    Uninstalling xformers-0.0.33.post1:
      Successfully uninstalled xformers-0.0.33.post1
Successfully installed xformers-0.0.34.dev1096

[notice] A new release of pip is available: 24.3.1 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
model, tokenizer = load_model("/content/lora_model")

==((====))==  Unsloth 2025.10.11: Fast Llama patching. Transformers: 4.55.4.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.8.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.4.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.32.post2. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/2.35G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/234 [00:00<?, ?B/s]

Unsloth 2025.10.11 patched 28 layers with 28 QKV layers, 28 O layers and 28 MLP layers.

In [ ]:
import pandas as pd
from tqdm import tqdm
import evaluate
from jiwer import cer, wer

### 📊 Evaluation Metrics for Transliteration Model

This section explains the evaluation metrics commonly used to assess **Jawi ↔ Rumi transliteration** quality.  
We use four main metrics: **BLEU**, **ChrF**, **CER**, and **WER**.

---

##### 🧮 1. BLEU (Bilingual Evaluation Understudy)

**Purpose:**  
Measures how closely the predicted output matches the reference at the **word level**.

**How it works:**
- Compares overlapping **n-grams** (1-gram, 2-gram, etc.) between the model output and the reference text.
- Produces a score between `0` and `1`.

**Interpretation:**
| BLEU Score | Meaning |
|-------------|----------|
| 1.0 | Perfect match |
| 0.7–1.0 | Excellent |
| 0.4–0.7 | Moderate |
| <0.4 | Weak |

**Notes:**
- BLEU is case- and token-sensitive.
- Works well for **translation**, but can be harsh for **transliteration**, since one wrong letter can drop the score.

---

##### 🔡 2. ChrF (Character F-score)

**Purpose:**  
Evaluates character-level accuracy — ideal for **transliteration tasks**.

**How it works:**
- Measures **character n-gram** overlaps instead of words.
- Computes the **F1-score** (precision + recall) for characters.
- Returns a score between `0` and `100`.

**Interpretation:**
| ChrF Score | Meaning |
|-------------|----------|
| 100 | Perfect match |
| >90 | Excellent |
| 70–90 | Good |
| <70 | Many character errors |

**Notes:**
- Better suited than BLEU for transliteration.
- More robust against spacing and word boundary issues.

---

##### 🧠 3. CER (Character Error Rate)
---
**Purpose:**  
Measures literal character accuracy.

**How it works:**
- Based on **edit distance** (Levenshtein distance).
- Calculates how many characters must be **inserted, deleted, or substituted** to match the reference.
- Formula:  
  \[
  CER = \frac{\text{Edits}}{\text{Total Reference Characters}}
  \]

**Interpretation:**
| CER Score | Meaning |
|------------|----------|
| 0.0 | Perfect |
| 0.1 | 10% of characters wrong |
| 0.3+ | Weak performance |

**Notes:**
- Every single character counts (including punctuation, spacing, and casing).
- Very precise for **transliteration fidelity**.

### 2. Compute evaluation metrics

#### Evaluation Metrics Function

In [ ]:
def compute_metrics(predictions, references):
    """
    Compute BLEU, ChrF, CER, and WER scores for text predictions.
    Returns values rounded to 4 decimal places.
    """

    # Convert to string list
    predictions = [str(p) for p in predictions]
    references = [str(r) for r in references]

    # Load metrics
    bleu_metric = evaluate.load("bleu")
    chrf_metric = evaluate.load("chrf")

    # Compute BLEU
    bleu_score = bleu_metric.compute(
        predictions=predictions,
        references=[[r] for r in references]  # BLEU expects nested lists
    )["bleu"]

    # Compute ChrF
    chrf_score = chrf_metric.compute(
        predictions=predictions,
        references=[[r] for r in references]
    )["score"]

    # Compute CER & WER
    cer_score = cer(references, predictions)
    wer_score = wer(references, predictions)

    # Return rounded results
    return {
        "BLEU": round(bleu_score, 4),
        "ChrF": round(chrf_score, 4),
        "CER": round(cer_score, 4),
        "WER": round(wer_score, 4)
    }

### 3. Inference

#### Transliteration Generation Function
Example: Jawi → Rumi

In [ ]:
from unsloth.chat_templates import get_chat_template
from transformers import TextStreamer
import torch

def transliterate_generate(model, tokenizer, prompt: str,
                           direction: str = "jawi2rumi",
                           chat_template="llama-3.1",
                           max_new_tokens=128,
                           temperature=0.1,
                           min_p=0.1):
    """
    Generate transliteration (Jawi↔Rumi) using Unsloth fine-tuned model.

    Args:
        model: Loaded FastLanguageModel
        tokenizer: Corresponding tokenizer
        prompt (str): Input text (either Jawi or Rumi)
        direction (str): Either 'jawi2rumi' or 'rumi2jawi'
        chat_template (str): Chat template used during training
        max_new_tokens (int): Max tokens to generate
        temperature (float): Sampling temperature
        min_p (float): Minimum nucleus sampling probability

    Returns:
        str: Generated transliteration
    """

    # Ensure correct chat template
    tokenizer = get_chat_template(tokenizer, chat_template=chat_template)

    # Optional: live text streamer
    text_streamer = TextStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)

    # ✅ Set tag based on direction
    if direction not in ["jawi2rumi", "rumi2jawi"]:
        raise ValueError("Invalid direction. Use 'jawi2rumi' or 'rumi2jawi'.")

    messages = [
        {"role": "user", "content": f"<{direction}> {prompt}"},
    ]

    # Tokenize
    inputs = tokenizer.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_tensors="pt",
    ).to(model.device)

    # Attention mask
    attention_mask = inputs.ne(tokenizer.pad_token_id).long()

    # Generate
    with torch.no_grad():
        outputs = model.generate(
            input_ids=inputs,
            attention_mask=attention_mask,
            streamer=text_streamer,
            max_new_tokens=max_new_tokens,
            temperature=temperature,
            min_p=min_p,
        )

    generated = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # 🧹 Clean up Unsloth / Llama chat template junk
    if "assistant" in generated:
        generated = generated.split("assistant", 1)[-1]
    elif "<|assistant|>" in generated:
        generated = generated.split("<|assistant|>", 1)[-1]

    return generated.strip()

#### i. Sample single inference

In [ ]:
result = transliterate_generate(
    model,
    tokenizer,
    prompt="چينتا سجاتي اداله سوات ڤركارا يڠ مرجوع كڤد حقيقة باطن",
    direction="jawi2rumi"
)

Cinta sejati adalah suatu perkarangan yang merujuk kepada hakikat batin

#### ii. Multiple inference (compare side-by-side with actual dataset)

##### a. Manual examples

###### Evaluate manual examples function

In [ ]:
def evaluate_manual_examples(model, tokenizer, examples, direction="jawi2rumi", preview_rows=5):
    """
    Evaluate manual Jawi↔Rumi transliteration examples with metrics.

    Args:
        model: Fine-tuned Unsloth model
        tokenizer: Tokenizer for the model
        examples: List of dicts [{"Input": ..., "Actual": ...}, ...]
        direction: "jawi2rumi" or "rumi2jawi"
        preview_rows: Number of example rows to display in the output

    Returns:
        comparison_df: DataFrame with Input, Predicted, and Actual
        metrics: dict with BLEU, ChrF, CER, WER
    """
    manual_df = pd.DataFrame(examples)
    results = []

    # --- Generate predictions ---
    print(f"🪶 Transliteration Evaluation: {direction}")
    for i, row in tqdm(manual_df.iterrows(), total=len(manual_df), desc=f"Generating {direction}"):
        input_text = str(row["Input"])
        actual_output = str(row["Actual"])

        predicted_output = transliterate_generate(model, tokenizer, prompt=input_text, direction=direction)

        results.append({
            "No": i + 1,
            "Input": input_text,
            "Predicted": predicted_output.strip(),
            "Actual": actual_output.strip()
        })

    comparison_df = pd.DataFrame(results)
    pd.set_option('display.max_colwidth', 200)

    # --- Compute evaluation metrics ---
    metrics = compute_metrics(
        predictions=comparison_df["Predicted"].tolist(),
        references=comparison_df["Actual"].tolist()
    )

    # --- Display results ---
    print("\n📘 Example Predictions:")
    display(comparison_df.head(preview_rows))

    print("\n📊 Evaluation Metrics:")
    for k, v in metrics.items():
        print(f"{k}: {v:.4f}")

    return comparison_df, metrics

###### Example usage

In [ ]:
examples = [
    {"Input": "كمدين ممولڠكنڽ كڤد أصلڽ",
     "Actual": "Kemudian memulangkannya kepada asalnya"},
    # {"Input": "چينتا سجاتي اداله سوات ڤركارا يڠ مرجوع كڤد حقيقة باطن",
    #  "Actual": "Cinta sejati adalah suatu perkara yang merujuk kepada hakikat batin"}
]

comparison_df, metrics = evaluate_manual_examples(model, tokenizer, examples, direction="jawi2rumi")

🪶 Transliteration Evaluation: jawi2rumi

Generating jawi2rumi:   0%|          | 0/1 [00:00<?, ?it/s]

Kemudian memulangkannya kepada asalnya

Generating jawi2rumi: 100%|██████████| 1/1 [00:00<00:00,  1.02it/s]

📘 Example Predictions:

,No,Input,Predicted,Actual
0,1,كمدين ممولڠكنڽ كڤد أصلڽ,Kemudian memulangkannya kepada asalnya,Kemudian memulangkannya kepada asalnya

📊 Evaluation Metrics:
BLEU: 1.0000
ChrF: 100.0000
CER: 0.0000
WER: 0.0000

##### b. N test samples (random)

###### Unified Evaluation Function (with random_state + progress info)

In [ ]:
def evaluate_transliteration(
    model,
    tokenizer,
    file_path: str,
    direction: str = "jawi2rumi",
    sheet_name: str = None,      # None = evaluate all sheets
    n_samples: int = 10,         # number of samples per sheet
    preview_rows: int = 5,       # how many rows to display
    random_state: int = 42,      # seed for reproducibility / random sampling
    save_results: bool = False   # save CSV summaries
):
    """
    Evaluate Jawi↔Rumi transliteration model on one or all Excel sheets.

    Args:
        model: fine-tuned Unsloth model
        tokenizer: corresponding tokenizer
        file_path: path to Excel dataset
        direction: "jawi2rumi" or "rumi2jawi"
        sheet_name: specific sheet to evaluate, or None for all
        n_samples: number of random samples per sheet
        preview_rows: number of sample predictions to display
        random_state: random seed for sampling reproducibility
        save_results: whether to save CSV outputs
    """

    # Define input/output column names
    input_col = "Jawi" if direction == "jawi2rumi" else "Rumi"
    target_col = "Rumi" if direction == "jawi2rumi" else "Jawi"

    results_summary = []

    # --- Determine which sheets to process ---
    if sheet_name:
        sheet_list = [sheet_name]
    else:
        sheet_list = pd.ExcelFile(file_path).sheet_names
        print(f"📄 Found {len(sheet_list)} sheets: {sheet_list}\n")

    # --- Iterate over sheets ---
    for idx, sheet in enumerate(sheet_list, start=1):
        print(f"\n🟢 [{idx}/{len(sheet_list)}] Now processing sheet: '{sheet}' ...")

        df = pd.read_excel(file_path, sheet_name=sheet)

        # Skip if missing columns
        if input_col not in df.columns or target_col not in df.columns:
            print(f"⚠️ Skipping '{sheet}' (missing {input_col}/{target_col})")
            continue

        # Sample data with random_state
        sample_df = df.sample(min(n_samples, len(df)), random_state=random_state).reset_index(drop=True)

        # Generate predictions
        rows = []
        for i, row in tqdm(sample_df.iterrows(), total=len(sample_df), desc=f"🔄 Generating {direction} [{sheet}]"):
            input_text = str(row[input_col])
            actual_output = str(row[target_col])
            predicted_output = transliterate_generate(model, tokenizer, prompt=input_text, direction=direction)
            rows.append({
                "Sheet": sheet,
                "No": i + 1,
                "Input": input_text,
                "Predicted": predicted_output.strip(),
                "Actual": actual_output.strip()
            })

        # Create comparison DataFrame
        comparison_df = pd.DataFrame(rows)

        # Compute metrics
        metrics = compute_metrics(
            predictions=comparison_df["Predicted"].tolist(),
            references=comparison_df["Actual"].tolist()
        )

        results_summary.append({
            "Sheet": sheet,
            "Samples": len(sample_df),
            **metrics,
        })

        # Optional preview
        print(f"\n📘 Sample Predictions from sheet '{sheet}':")
        display(comparison_df.head(preview_rows))

        # Save per-sheet comparison if enabled
        if save_results:
            out_path = f"results_{sheet}_{direction}.csv"
            comparison_df.to_csv(out_path, index=False)
            print(f"💾 Saved detailed results to: {out_path}")

        print("-" * 80)  # Separator between sheets

    # --- Create overall summary ---
    summary_df = pd.DataFrame(results_summary)
    print("\n📊 Overall Evaluation Summary:")
    display(summary_df)

    if save_results:
        summary_path = f"evaluation_summary_{direction}.csv"
        summary_df.to_csv(summary_path, index=False)
        print(f"✅ Saved metrics summary to '{summary_path}'")

    return summary_df

###### Option 1 — Evaluate a single sheet

In [ ]:
evaluate_transliteration(
    model,
    tokenizer,
    file_path="/content/From AJM - Risalah Untuk Kaum Muslimin.xlsx",
    sheet_name="Page 1-15(Aiman)",
    direction="jawi2rumi",
    n_samples=10,
    random_state=7,   # try different seeds to sample other rows
    save_results=False
)

🟢 [1/1] Now processing sheet: 'Page 1-15(Aiman)' ...

🔄 Generating jawi2rumi [Page 1-15(Aiman)]:   0%|          | 0/10 [00:00<?, ?it/s]

Tetek Adam Belum Terang

🔄 Generating jawi2rumi [Page 1-15(Aiman)]:  10%|█         | 1/10 [00:00<00:07,  1.19it/s]

Maka sesungguhnya hajatku kini tiada lain daripada berdayaousiah kepada Muslimin yang dakasihinya - suat rasulah yang kecilain dengan maksud antuq mengemukakannya suat pendangan yang keranya diizinkan Allah c diapit jawa memberi sedikia sebabnya petajuk, dan in shaa Allah membantunya pul memimempinamukannya kajalan yang benar.

🔄 Generating jawi2rumi [Page 1-15(Aiman)]:  20%|██        | 2/10 [00:08<00:36,  4.59s/it]

Toladan terbaik bagi anak Adam dan Rahmat Ilahi bagi seklin alam.

🔄 Generating jawi2rumi [Page 1-15(Aiman)]:  30%|███       | 3/10 [00:09<00:22,  3.16s/it]

Maka yang Jahil di antara Masyarakat Melayu dan Menganjegap bahawa bukanlah cermin itu yang kita tahu atau kita cahaya yang kasar berkarat, akentetapi bahawa menentang hakikat yang dibayangkan oleh cermin itu juga yang kelam dan ketut dan penah dengannya cahaya dan nuada korengan sifat-sifat kesuatin dan kemurnian dan klauhuran dan keagungan sijati.

🔄 Generating jawi2rumi [Page 1-15(Aiman)]:  40%|████      | 4/10 [00:17<00:29,  4.88s/it]

Dalam resepsi debali akan agung

🔄 Generating jawi2rumi [Page 1-15(Aiman)]:  50%|█████     | 5/10 [00:17<00:17,  3.41s/it]

Sebagainya nabi akan terus berjalan

🔄 Generating jawi2rumi [Page 1-15(Aiman)]:  60%|██████    | 6/10 [00:18<00:10,  2.56s/it]

Stroesnya kepad klawaragananya yang dipersusuhkan kesuatuannya, yang nasibnya tumboh teguh dalam segara, laksana pohon yang akan membaham merangkum buaya dan dauannya melambai delangita murai.

🔄 Generating jawi2rumi [Page 1-15(Aiman)]:  70%|███████   | 7/10 [00:22<00:09,  3.03s/it]

Dalam keadaan mereka?;

🔄 Generating jawi2rumi [Page 1-15(Aiman)]:  80%|████████  | 8/10 [00:23<00:04,  2.27s/it]

Pemilik kuas yang mahakui

🔄 Generating jawi2rumi [Page 1-15(Aiman)]:  90%|█████████ | 9/10 [00:24<00:01,  1.79s/it]

Tetekel kalam bolum bersurat

🔄 Generating jawi2rumi [Page 1-15(Aiman)]: 100%|██████████| 10/10 [00:24<00:00,  2.49s/it]

📘 Sample Predictions from sheet 'Page 1-15(Aiman)':

,Sheet,No,Input,Predicted,Actual
0,Page 1-15(Aiman),1,تتكل آدم بلوم ترايڠة,Tetek Adam Belum Terang,"Tatkala Adam belum teringat,"
1,Page 1-15(Aiman),2,مک سسڠݢوهڽ حاجةكو كيني تيادا لاࢨن درڤد برداياؤ...,Maka sesungguhnya hajatku kini tiada lain dari...,Maka sesungguhnya hajatku kini tiada lain dari...
2,Page 1-15(Aiman),3,تولادان ترباࢨق بݢ انق آدم دان رحمة إلــٰهي بݢ ...,Toladan terbaik bagi anak Adam dan Rahmat Ilah...,tauladan terbaik bagi anak Adam dan rahmat Ila...
3,Page 1-15(Aiman),4,مک يڠ جاهل دأنتارا مأنسي اكن مليهة دان مڠڠݢڤ ب...,Maka yang Jahil di antara Masyarakat Melayu da...,Maka yang jahil di antara manusia akan melihat...
4,Page 1-15(Aiman),5,دالم رهسيا دباليْ اݢوڠ,Dalam resepsi debali akan agung,"Dalam rahasia di Balai Agung,"

--------------------------------------------------------------------------------

📊 Overall Evaluation Summary:

              Sheet  Samples      BLEU       ChrF       CER       WER
0  Page 1-15(Aiman)       10  0.185728  61.243499  0.259707  0.588957

              Sheet  Samples      BLEU       ChrF       CER       WER
0  Page 1-15(Aiman)       10  0.185728  61.243499  0.259707  0.588957

###### Option 2 — Evaluate all sheets automatically

In [ ]:
summary_df = evaluate_transliteration(
    model,
    tokenizer,
    file_path="/content/From AJM - Risalah Untuk Kaum Muslimin.xlsx",
    direction="jawi2rumi",
    n_samples=1,
    random_state=7,   # try different seeds to sample other rows
    save_results=False
)

📄 Found 10 sheets: ['Page 1-15(Aiman)', 'Page 16-30 (Hasan)', 'Page 31-45 (Amir)', '46-60 (Sakinah)', '61-75 (Mohaidin)', '76-90 Amir', '91-105 Hasan', '106-120 Sakinah', '121-135 Mohaidin', '135-144 Aiman']


🟢 [1/10] Now processing sheet: 'Page 1-15(Aiman)' ...

🔄 Generating jawi2rumi [Page 1-15(Aiman)]:   0%|          | 0/1 [00:00<?, ?it/s]

Tetek Adam Belum Terang

🔄 Generating jawi2rumi [Page 1-15(Aiman)]: 100%|██████████| 1/1 [00:00<00:00,  1.43it/s]

📘 Sample Predictions from sheet 'Page 1-15(Aiman)':

,Sheet,No,Input,Predicted,Actual
0,Page 1-15(Aiman),1,تتكل آدم بلوم ترايڠة,Tetek Adam Belum Terang,"Tatkala Adam belum teringat,"

--------------------------------------------------------------------------------

🟢 [2/10] Now processing sheet: 'Page 16-30 (Hasan)' ...

🔄 Generating jawi2rumi [Page 16-30 (Hasan)]:   0%|          | 0/1 [00:00<?, ?it/s]

Stelah merenungkan dengan bawaan dan tabiat alam semesta, merik dipati peribadikan yang menyelakkan antara keadaan tabiat alam seleraannya dan keadaan alam manis.

🔄 Generating jawi2rumi [Page 16-30 (Hasan)]: 100%|██████████| 1/1 [00:03<00:00,  3.42s/it]

📘 Sample Predictions from sheet 'Page 16-30 (Hasan)':

,Sheet,No,Input,Predicted,Actual
0,Page 16-30 (Hasan),1,ستله مرنوڠكن باوأن دان طبيعة عالم سمستا، مريک ...,Stelah merenungkan dengan bawaan dan tabiat al...,Setelah merenungkan bawaan dan tabiat alam sem...

--------------------------------------------------------------------------------

🟢 [3/10] Now processing sheet: 'Page 31-45 (Amir)' ...

🔄 Generating jawi2rumi [Page 31-45 (Amir)]:   0%|          | 0/1 [00:00<?, ?it/s]

Banyak, ada yang tiada berfungu, ada juga yang bukan ilmu, meskipun dikelirukan dengan ilmu.

🔄 Generating jawi2rumi [Page 31-45 (Amir)]: 100%|██████████| 1/1 [00:02<00:00,  2.06s/it]

📘 Sample Predictions from sheet 'Page 31-45 (Amir)':

,Sheet,No,Input,Predicted,Actual
0,Page 31-45 (Amir),1,باࢨق،‭ ‬ادا‭ ‬يڠ‭ ‬تيادا‭ ‬برݢونا،‭ ‬ادا‭ ‬جوݢ...,"Banyak, ada yang tiada berfungu, ada juga yang...",nan

--------------------------------------------------------------------------------

🟢 [4/10] Now processing sheet: '46-60 (Sakinah)' ...

🔄 Generating jawi2rumi [46-60 (Sakinah)]:   0%|          | 0/1 [00:00<?, ?it/s]

Selangketan pula faham pertimbangan yang sesama antara bahagian kubudayan yang bersifat bendanya dan yang tiada bersifat bendanya harus senantiasa diingatati dengan jelas spai daapata menghindarken kekliwaran yang muongkin akan timbul dalam menilai unsur 2 kubudayan dengan nilaian yang sempurna,

🔄 Generating jawi2rumi [46-60 (Sakinah)]: 100%|██████████| 1/1 [00:06<00:00,  6.49s/it]

📘 Sample Predictions from sheet '46-60 (Sakinah)':

,Sheet,No,Input,Predicted,Actual
0,46-60 (Sakinah),1,سلنجوتڽ‭ ‬ڤول‭ ‬فهم‭ ‬ڤرتيمباڠن‭ ‬يڠ‭ ‬سقسام‭ ...,Selangketan pula faham pertimbangan yang sesam...,Selanjutnya pula faham pertimbangan yang saksa...

--------------------------------------------------------------------------------

🟢 [5/10] Now processing sheet: '61-75 (Mohaidin)' ...

🔄 Generating jawi2rumi [61-75 (Mohaidin)]:   0%|          | 0/1 [00:00<?, ?it/s]

Mengenai faham yang disebut sekular, dan mengenai pensekularan dan sekularisme itu tidak nanti akan dehuriken dengan lebih lengua dan perenggan 71 sturusan.

🔄 Generating jawi2rumi [61-75 (Mohaidin)]: 100%|██████████| 1/1 [00:03<00:00,  3.24s/it]

📘 Sample Predictions from sheet '61-75 (Mohaidin)':

,Sheet,No,Input,Predicted,Actual
0,61-75 (Mohaidin),1,مڠناࢨ‭ ‬فهم‭ ‬يڠ‭ ‬دسبوة‭ ‬سيكولر،‭ ‬دان‭ ‬مڠن...,"Mengenai faham yang disebut sekular, dan menge...","Mengenai faham yang disebut sekular, dan menge..."

--------------------------------------------------------------------------------

🟢 [6/10] Now processing sheet: '76-90 Amir' ...

🔄 Generating jawi2rumi [76-90 Amir]:   0%|          | 0/1 [00:00<?, ?it/s]

Penyediaan itu penyerapan adab dalam diri.

🔄 Generating jawi2rumi [76-90 Amir]: 100%|██████████| 1/1 [00:01<00:00,  1.36s/it]

📘 Sample Predictions from sheet '76-90 Amir':

,Sheet,No,Input,Predicted,Actual
0,76-90 Amir,1,ڤنديديقكن‭ ‬ايت‭ ‬ڤڽراڤن‭ ‬أدب‭ ‬كدالم‭ ‬ديري‭.‬,Penyediaan itu penyerapan adab dalam diri.,nan

--------------------------------------------------------------------------------

🟢 [7/10] Now processing sheet: '91-105 Hasan' ...

🔄 Generating jawi2rumi [91-105 Hasan]:   0%|          | 0/1 [00:00<?, ?it/s]

Dan yang tiada memadai terhadap kepemimpinan yang dakhindari oleh Islam.

🔄 Generating jawi2rumi [91-105 Hasan]: 100%|██████████| 1/1 [00:01<00:00,  1.68s/it]

📘 Sample Predictions from sheet '91-105 Hasan':

,Sheet,No,Input,Predicted,Actual
0,91-105 Hasan,1,دان‭ ‬يڠ‭ ‬تيادا‭ ‬ممداࢨ‭ ‬طرف‭ ‬كڤيمڤينن‭ ‬يڠ...,Dan yang tiada memadai terhadap kepemimpinan y...,nan

--------------------------------------------------------------------------------

🟢 [8/10] Now processing sheet: '106-120 Sakinah' ...

🔄 Generating jawi2rumi [106-120 Sakinah]:   0%|          | 0/1 [00:00<?, ?it/s]

Mereka berpautan dengan cara sallalu melauangkan 2 kenai ayat dalam al-Quran al-Karim danaman terdapat kesetan Allah c berfirman menitah rasul Allah g sepiaya mengesak bahawa dia di – « – hanyalah manisi serta kamera suam – » –

🔄 Generating jawi2rumi [106-120 Sakinah]: 100%|██████████| 1/1 [00:05<00:00,  5.44s/it]

📘 Sample Predictions from sheet '106-120 Sakinah':

,Sheet,No,Input,Predicted,Actual
0,106-120 Sakinah,1,مريک‭ ‬بربواة‭ ‬بݢيني‭ ‬دڠن‭ ‬چارا‭ ‬سلالو‭ ‬م...,Mereka berpautan dengan cara sallalu melauangk...,Mereka berbuat begini dengan cara selalu melau...

--------------------------------------------------------------------------------

🟢 [9/10] Now processing sheet: '121-135 Mohaidin' ...

🔄 Generating jawi2rumi [121-135 Mohaidin]:   0%|          | 0/1 [00:00<?, ?it/s]

nan

🔄 Generating jawi2rumi [121-135 Mohaidin]: 100%|██████████| 1/1 [00:00<00:00,  3.50it/s]

📘 Sample Predictions from sheet '121-135 Mohaidin':

              Sheet  No Input Predicted Actual
0  121-135 Mohaidin   1   nan       nan    nan

--------------------------------------------------------------------------------

🟢 [10/10] Now processing sheet: '135-144 Aiman' ...

🔄 Generating jawi2rumi [135-144 Aiman]:   0%|          | 0/1 [00:00<?, ?it/s]

Penggunaan alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta alam semesta

🔄 Generating jawi2rumi [135-144 Aiman]: 100%|██████████| 1/1 [00:08<00:00,  8.65s/it]

📘 Sample Predictions from sheet '135-144 Aiman':

,Sheet,No,Input,Predicted,Actual
0,135-144 Aiman,1,ڤڠوسوڠن‭ ‬عالـــم‭ ‬طبيعـــي‭ ‬دري‭ ‬ســـبارڠ‭...,Penggunaan alam semesta alam semesta alam seme...,nan

--------------------------------------------------------------------------------

📊 Overall Evaluation Summary:

                Sheet  Samples      BLEU        ChrF         CER        WER
0    Page 1-15(Aiman)        1  0.000000   22.250796    0.392857   0.750000
1  Page 16-30 (Hasan)        1  0.364061   76.336389    0.160256   0.380952
2   Page 31-45 (Amir)        1  0.000000    7.455931   29.666667  14.000000
3     46-60 (Sakinah)        1  0.308590   78.445886    0.125850   0.368421
4    61-75 (Mohaidin)        1  0.553523   78.793751    0.125000   0.238095
5          76-90 Amir        1  0.000000   17.885220   13.000000   6.000000
6        91-105 Hasan        1  0.000000   14.219825   23.000000  10.000000
7     106-120 Sakinah        1  0.000000   46.075313    0.430147   0.914286
8    121-135 Mohaidin        1  0.000000  100.000000    0.000000   0.000000
9       135-144 Aiman        1  0.000000    2.310968  136.666667  63.000000

In [ ]:
def compute_metrics(predictions, references):
    """
    Compute BLEU, ChrF, CER, and WER scores for text predictions.
    Returns values rounded to 4 decimal places.
    """

    # Convert to string list
    predictions = [str(p) for p in predictions]
    references = [str(r) for r in references]

    # Load metrics
    bleu_metric = evaluate.load("bleu")
    chrf_metric = evaluate.load("chrf")

    # Compute BLEU
    bleu_score = bleu_metric.compute(
        predictions=predictions,
        references=[[r] for r in references]  # BLEU expects nested lists
    )["bleu"]

    # Compute ChrF
    chrf_score = chrf_metric.compute(
        predictions=predictions,
        references=[[r] for r in references]
    )["score"]

    # Compute CER & WER
    cer_score = cer(references, predictions)
    wer_score = wer(references, predictions)

    # Return rounded results
    return {
        "BLEU": round(bleu_score, 4),
        "ChrF": round(chrf_score, 4),
        "CER": round(cer_score, 4),
        "WER": round(wer_score, 4)
    }